services:
  - type: web
    name: portfolio-rosario
    runtime: java
    buildCommand: chmod +x mvnw && ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 21